# Generated by Django 3.0.4 on 2020-03-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_auto_20200320_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='is_qc',
            field=models.BooleanField(),
        ),
    ]
