# Generated by Django 3.0.4 on 2020-03-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_case_is_complex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='is_rejected',
            field=models.BooleanField(blank=True),
        ),
    ]
