# Generated by Django 3.0.4 on 2020-03-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_auto_20200321_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='comments',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
