# Generated by Django 3.0.4 on 2020-03-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_case_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='comments',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='case',
            name='is_rejected',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
